# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ahwr-public-user-ui:
    build:
      target: development
    image: ahwr-public-user-ui-development
    container_name: ahwr-public-user-ui-development
    environment:
      USE_PRETTY_PRINT: ${USE_PRETTY_PRINT:-true}
      DEV_LOGIN_ENABLED: ${DEV_LOGIN_ENABLED:-true}
    ports:
      - "3003:3000"
      - "9232:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - ahwr-local

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ahwr-local

# Make sure you have this network locally 'ahwr-local' (created in /scripts/start)
networks:
  ahwr-local:
    external: true

volumes:
  azurite_data:
  redis_data:
