# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ahwr-public-user-ui:
    build:
      target: development
    environment:
      NODE_ENV: test
    image: ahwr-public-user-ui-development
    container_name: ahwr-public-user-ui-test
    command: npm run test
    volumes:
      - ./test-output:/home/node/test-output
