export const dashboardRoutes = {
  manageYourClaims: "/vet-visits",
  poultryManageYourClaims: "/poultry/manage-claims",
  checkDetails: "/check-details",
  selectFunding: "/select-funding",
};

export const dashboardViews = {
  selectFunding: "select-funding",
};

export const supportRoutes = {
  health: "/health",
  cookies: "/cookies",
  accessibility: "/accessibility",
  missingRoutes: "/missing-routes",
  assets: "/assets",
  updateDetails: "/update-details",
};

export const loginRoutes = {
  signIn: "/sign-in",
  signInOidc: "/signin-oidc",
  signOut: "/sign-out",
  cannotSignIn: "/cannot-sign-in",
  devLandingPage: "/dev-landing-page",
  devSignIn: "/dev-sign-in",
};

export const applyRoutes = {
  youCanClaimMultiple: "/you-can-claim-multiple",
  timings: "/timings",
  numbers: "/numbers",
  declaration: "/declaration",
  offerRejected: "/offer-rejected",
};

export const poultryApplyRoutes = {
  whatYouCanClaim: "/poultry/what-you-can-claim",
  timings: "/poultry/timings",
  minimumNumber: "/poultry/minimum-number",
  agreementOffer: "/poultry/agreement-offer",
};

export const applyViews = {
  youCanClaimMultiple: "livestock/apply/you-can-claim-multiple",
  timings: "livestock/apply/timings",
  numbers: "livestock/apply/numbers",
  declaration: "livestock/apply/declaration",
  offerRejected: "livestock/apply/offer-rejected",
  confirmation: "livestock/apply/confirmation",
};

export const poultryApplyViews = {
  youCanClaimMultiple: "poultry/apply/what-you-can-claim",
  timings: "poultry/apply/timings",
  minimumNumber: "poultry/apply/minimum-number",
  agreementOffer: "poultry/apply/agreement-offer",
  offerRejected: "poultry/apply/offer-rejected",
  termsRejected: "poultry/apply/terms-rejected",
  confirmation: "poultry/apply/confirmation",
};

export const claimRoutes = {
  assuranceScheme: "/assurance-scheme",
  biosecurityException: "/biosecurity-exception",
  biosecurity: "/biosecurity",
  checkAnswers: "/check-answers",
  checkHerdDetails: "/check-herd-details",
  confirmation: "/confirmation",
  dairyFollowUpDateException: "/dairy-follow-up-date-exception",
  dateOfTestingException: "/date-of-testing-exception",
  dateOfTesting: "/date-of-testing",
  dateOfVisitException: "/date-of-visit-exception",
  dateOfVisit: "/date-of-visit",
  diseaseStatus: "/disease-status",
  enterCphNumber: "/enter-cph-number",
  enterHerdDetails: "/enter-herd-details",
  enterHerdName: "/enter-herd-name",
  herdOthersOnSbi: "/herd-others-on-sbi",
  multipleSpeciesDateException: "/multiple-species-date-exception",
  typeOfSamplesTaken: "/type-of-samples-taken",
  numberOfFluidOralSamplesException: "/number-of-fluid-oral-samples-exception",
  numberOfFluidOralSamples: "/number-of-fluid-oral-samples",
  numberOfBloodSamplesException: "/number-of-blood-samples-exception",
  numberOfBloodSamples: "/number-of-blood-samples",
  numberOfSamplesTestedException: "/number-of-samples-tested-exception",
  numberOfSamplesTested: "/number-of-samples-tested",
  numberOfSpeciesException: "/number-of-species-exception",
  numberOfSpeciesPigsException: "/number-of-species-pigs-exception",
  numberOfSpeciesSheepException: "/number-of-species-sheep-exception",
  numberOfSpeciesTested: "/number-of-species-tested",
  piHuntAllAnimalsException: "/pi-hunt-all-animals-exception",
  piHuntAllAnimals: "/pi-hunt-all-animals",
  piHuntException: "/pi-hunt-exception",
  piHuntRecommendedException: "/pi-hunt-recommended-exception",
  piHuntRecommended: "/pi-hunt-recommended",
  piHunt: "/pi-hunt",
  pigsElisaResult: "/pigs-elisa-result",
  pigsGeneticSequencing: "/pigs-genetic-sequencing",
  pigsPcrResult: "/pigs-pcr-result",
  sameHerdException: "/same-herd-exception",
  sameHerd: "/same-herd",
  selectTheHerdDateException: "/select-the-herd-date-exception",
  selectTheHerdException: "/select-the-herd-exception",
  selectTheHerd: "/select-the-herd",
  sheepEndemicsPackage: "/sheep-endemics-package",
  sheepTestResults: "/sheep-test-results",
  sheepTests: "/sheep-tests",
  speciesNumbersException: "/species-numbers-exception",
  speciesNumbers: "/species-numbers",
  testResults: "/test-results",
  testUrnException: "/test-urn-exception",
  testUrn: "/test-urn",
  vaccination: "/vaccination",
  vetName: "/vet-name",
  vetRcvs: "/vet-rcvs",
  vetVisitsReviewTestResults: "/vet-visits-review-test-results",
  whichSpecies: "/which-species",
  whichTypeOfReviewDairyFollowUpException: "/which-type-of-review-dairy-follow-up-exception",
  whichTypeOfReviewException: "/which-type-of-review-exception",
  whichTypeOfReview: "/which-type-of-review",
  youCannotClaim: "/you-cannot-claim",
};

export const claimViews = {
  assuranceScheme: "livestock/claim/assurance-scheme",
  biosecurityException: "livestock/claim/biosecurity-exception",
  biosecurity: "livestock/claim/biosecurity",
  checkAnswers: "livestock/claim/check-answers",
  checkHerdDetails: "livestock/claim/check-herd-details",
  confirmation: "livestock/claim/confirmation",
  dairyFollowUpDateException: "livestock/claim/dairy-follow-up-date-exception",
  dateOfTestingException: "livestock/claim/date-of-testing-exception",
  dateOfTesting: "livestock/claim/date-of-testing",
  dateOfVisitException: "livestock/claim/date-of-visit-exception",
  dateOfVisit: "livestock/claim/date-of-visit",
  diseaseStatus: "livestock/claim/disease-status",
  enterCphNumber: "livestock/claim/enter-cph-number",
  enterHerdDetails: "livestock/claim/enter-herd-details",
  enterHerdName: "livestock/claim/enter-herd-name",
  herdOthersOnSbi: "livestock/claim/herd-others-on-sbi",
  multipleSpeciesDateException: "livestock/claim/multiple-species-date-exception",
  typeOfSamplesTaken: "livestock/claim/type-of-samples-taken",
  numberOfFluidOralSamplesException: "livestock/claim/number-of-fluid-oral-samples-exception",
  numberOfFluidOralSamples: "livestock/claim/number-of-fluid-oral-samples",
  numberOfBloodSamplesException: "livestock/claim/number-of-blood-samples-exception",
  numberOfBloodSamples: "livestock/claim/number-of-blood-samples",
  numberOfSamplesTestedException: "livestock/claim/number-of-samples-tested-exception",
  numberOfSamplesTested: "livestock/claim/number-of-samples-tested",
  numberOfSpeciesException: "livestock/claim/number-of-species-exception",
  numberOfSpeciesPigsException: "livestock/claim/number-of-species-pigs-exception",
  numberOfSpeciesSheepException: "livestock/claim/number-of-species-sheep-exception",
  numberOfSpeciesTested: "livestock/claim/number-of-species-tested",
  piHuntAllAnimalsException: "livestock/claim/pi-hunt-all-animals-exception",
  piHuntAllAnimals: "livestock/claim/pi-hunt-all-animals",
  piHuntException: "livestock/claim/pi-hunt-exception",
  piHuntRecommendedException: "livestock/claim/pi-hunt-recommended-exception",
  piHuntRecommended: "livestock/claim/pi-hunt-recommended",
  piHunt: "livestock/claim/pi-hunt",
  pigsElisaResult: "livestock/claim/pigs-elisa-result",
  pigsGeneticSequencing: "livestock/claim/pigs-genetic-sequencing",
  pigsPcrResult: "livestock/claim/pigs-pcr-result",
  sameHerdException: "livestock/claim/same-herd-exception",
  sameHerd: "livestock/claim/same-herd",
  selectTheHerdDateException: "livestock/claim/select-the-herd-date-exception",
  selectTheHerdException: "livestock/claim/select-the-herd-exception",
  selectTheHerd: "livestock/claim/select-the-herd",
  sheepEndemicsPackage: "livestock/claim/sheep-endemics-package",
  sheepTestResults: "livestock/claim/sheep-test-results",
  sheepTests: "livestock/claim/sheep-tests",
  speciesNumbersException: "livestock/claim/species-numbers-exception",
  speciesNumbers: "livestock/claim/species-numbers",
  testResults: "livestock/claim/test-results",
  testUrnException: "livestock/claim/test-urn-exception",
  testUrn: "livestock/claim/test-urn",
  vaccination: "livestock/claim/vaccination",
  vetName: "livestock/claim/vet-name",
  vetRcvs: "livestock/claim/vet-rcvs",
  vetVisitsReviewTestResults: "livestock/claim/vet-visits-review-test-results",
  whichSpecies: "livestock/claim/which-species",
  whichTypeOfReviewDairyFollowUpException:
    "livestock/claim/which-type-of-review-dairy-follow-up-exception",
  whichTypeOfReviewException: "livestock/claim/which-type-of-review-exception",
  whichTypeOfReview: "livestock/claim/which-type-of-review",
  youCannotClaim: "livestock/claim/you-cannot-claim",
};

export const poultryClaimRoutes = {
  biosecurity: "/poultry/biosecurity",
  biosecurityUsefulness: "/poultry/biosecurity-usefulness",
  changesInBiosecurity: "/poultry/changes-in-biosecurity",
  checkAnswers: "/poultry/check-answers",
  checkSiteDetails: "/poultry/check-site-details",
  confirmation: "/poultry/confirmation",
  costOfChanges: "/poultry/cost-of-changes",
  dateOfVisit: "/poultry/date-of-visit",
  enterSiteName: "/poultry/site-name",
  enterCphNumber: "/poultry/cph",
  enterSiteDetails: "/poultry/enter-site-details",
  interview: "/poultry/interview",
  minimumNumberOfBirds: "/poultry/minimum-number-of-birds",
  poultryType: "/poultry/poultry-type",
  selectTheSite: "/poultry/select-site",
  sbiSites: "/poultry/sbi-sites",
  vetName: "/poultry/vet-name",
  vetRcvs: "/poultry/vet-rcvs",
};

export const poultryClaimViews = {
  biosecurity: "poultry/claim/biosecurity",
  biosecurityException: "poultry/claim/biosecurity-exception",
  biosecurityUsefulness: "poultry/claim/biosecurity-usefulness",
  cannotContinueTimingRules: "poultry/claim/cannot-continue-timing-rules",
  changesInBiosecurity: "poultry/claim/changes-in-biosecurity",
  checkAnswers: "poultry/claim/check-answers",
  confirmation: "poultry/claim/confirmation",
  costOfChanges: "poultry/claim/biosecurity-cost-of-changes",
  dateOfVisit: "poultry/claim/date-of-visit",
  interview: "poultry/claim/interview",
  enterSiteName: "poultry/claim/site-name",
  enterCphNumber: "poultry/claim/cph",
  minimumNumberOfBirds: "poultry/claim/minimum-number-of-birds",
  minimumNumberOfBirdsException: "poultry/claim/minimum-number-of-birds-exception",
  poultryType: "poultry/claim/poultry-type",
  selectTheSite: "poultry/claim/select-the-site",
  sbiSites: "poultry/claim/sbi-sites",
  vetRcvs: "poultry/claim/vet-rcvs",
  vetName: "poultry/claim/vet-name",
};

export const poultryApplyUrls = Object.values(poultryApplyRoutes);
export const poultryClaimUrls = Object.values(poultryClaimRoutes);
export const allPoultryRoutes = [
  ...poultryApplyUrls,
  dashboardRoutes.poultryManageYourClaims,
  ...poultryClaimUrls,
];
