export const dashboardRoutes = {
  manageYourClaims: "/vet-visits",
  poultryManageYourClaims: "/poultry/vet-visits",
  checkDetails: "/check-details",
  selectFunding: "/select-funding",
};

export const dashboardViews = {
  selectFunding: "select-funding",
};

export const supportRoutes = {
  health: "/health",
  cookies: "/cookies",
  accessibility: "/accessibility",
  missingRoutes: "/missing-routes",
  assets: "/assets",
  updateDetails: "/update-details",
};

export const loginRoutes = {
  signIn: "/sign-in",
  signInOidc: "/signin-oidc",
  signOut: "/sign-out",
  cannotSignIn: "/cannot-sign-in",
  devLandingPage: "/dev-landing-page",
  devSignIn: "/dev-sign-in",
};

export const applyRoutes = {
  youCanClaimMultiple: "/you-can-claim-multiple",
  timings: "/timings",
  numbers: "/numbers",
  declaration: "/declaration",
  offerRejected: "/offer-rejected",
};

export const poultryApplyRoutes = {
  youCanClaimMultiple: "/poultry/you-can-claim-multiple",
  timings: "/poultry/timings",
  numbers: "/poultry/numbers",
  declaration: "/poultry/declaration",
  offerRejected: "/poultry/offer-rejected",
};

export const applyViews = {
  youCanClaimMultiple: "apply/you-can-claim-multiple",
  timings: "apply/timings",
  numbers: "apply/numbers",
  declaration: "apply/declaration",
  offerRejected: "apply/offer-rejected",
  confirmation: "apply/confirmation",
};

export const poultryApplyViews = {
  youCanClaimMultiple: "poultry/apply/you-can-claim-multiple",
  timings: "poultry/apply/timings",
  numbers: "poultry/apply/numbers",
  declaration: "poultry/apply/declaration",
  offerRejected: "poultry/apply/offer-rejected",
  confirmation: "poultry/apply/confirmation",
};

export const claimRoutes = {
  assuranceScheme: "/assurance-scheme",
  biosecurityException: "/biosecurity-exception",
  biosecurity: "/biosecurity",
  checkAnswers: "/check-answers",
  checkHerdDetails: "/check-herd-details",
  confirmation: "/confirmation",
  dairyFollowUpDateException: "/dairy-follow-up-date-exception",
  dateOfTestingException: "/date-of-testing-exception",
  dateOfTesting: "/date-of-testing",
  dateOfVisitException: "/date-of-visit-exception",
  dateOfVisit: "/date-of-visit",
  diseaseStatus: "/disease-status",
  enterCphNumber: "/enter-cph-number",
  enterHerdDetails: "/enter-herd-details",
  enterHerdName: "/enter-herd-name",
  herdOthersOnSbi: "/herd-others-on-sbi",
  multipleSpeciesDateException: "/multiple-species-date-exception",
  typeOfSamplesTaken: "/type-of-samples-taken",
  numberOfFluidOralSamplesException: "/number-of-fluid-oral-samples-exception",
  numberOfFluidOralSamples: "/number-of-fluid-oral-samples",
  numberOfBloodSamplesException: "/number-of-blood-samples-exception",
  numberOfBloodSamples: "/number-of-blood-samples",
  numberOfSamplesTestedException: "/number-of-samples-tested-exception",
  numberOfSamplesTested: "/number-of-samples-tested",
  numberOfSpeciesException: "/number-of-species-exception",
  numberOfSpeciesPigsException: "/number-of-species-pigs-exception",
  numberOfSpeciesSheepException: "/number-of-species-sheep-exception",
  numberOfSpeciesTested: "/number-of-species-tested",
  piHuntAllAnimalsException: "/pi-hunt-all-animals-exception",
  piHuntAllAnimals: "/pi-hunt-all-animals",
  piHuntException: "/pi-hunt-exception",
  piHuntRecommendedException: "/pi-hunt-recommended-exception",
  piHuntRecommended: "/pi-hunt-recommended",
  piHunt: "/pi-hunt",
  pigsElisaResult: "/pigs-elisa-result",
  pigsGeneticSequencing: "/pigs-genetic-sequencing",
  pigsPcrResult: "/pigs-pcr-result",
  sameHerdException: "/same-herd-exception",
  sameHerd: "/same-herd",
  selectTheHerdDateException: "/select-the-herd-date-exception",
  selectTheHerdException: "/select-the-herd-exception",
  selectTheHerd: "/select-the-herd",
  sheepEndemicsPackage: "/sheep-endemics-package",
  sheepTestResults: "/sheep-test-results",
  sheepTests: "/sheep-tests",
  speciesNumbersException: "/species-numbers-exception",
  speciesNumbers: "/species-numbers",
  testResults: "/test-results",
  testUrnException: "/test-urn-exception",
  testUrn: "/test-urn",
  vaccination: "/vaccination",
  vetName: "/vet-name",
  vetRcvs: "/vet-rcvs",
  vetVisitsReviewTestResults: "/vet-visits-review-test-results",
  whichSpecies: "/which-species",
  whichTypeOfReviewDairyFollowUpException: "/which-type-of-review-dairy-follow-up-exception",
  whichTypeOfReviewException: "/which-type-of-review-exception",
  whichTypeOfReview: "/which-type-of-review",
  youCannotClaim: "/you-cannot-claim",
};

export const claimViews = {
  assuranceScheme: "claim/assurance-scheme",
  biosecurityException: "claim/biosecurity-exception",
  biosecurity: "claim/biosecurity",
  checkAnswers: "claim/check-answers",
  checkHerdDetails: "claim/check-herd-details",
  confirmation: "claim/confirmation",
  dairyFollowUpDateException: "claim/dairy-follow-up-date-exception",
  dateOfTestingException: "claim/date-of-testing-exception",
  dateOfTesting: "claim/date-of-testing",
  dateOfVisitException: "claim/date-of-visit-exception",
  dateOfVisit: "claim/date-of-visit",
  devSignIn: "claim/dev-sign-in",
  diseaseStatus: "claim/disease-status",
  enterCphNumber: "claim/enter-cph-number",
  enterHerdDetails: "claim/enter-herd-details",
  enterHerdName: "claim/enter-herd-name",
  herdOthersOnSbi: "claim/herd-others-on-sbi",
  multipleSpeciesDateException: "claim/multiple-species-date-exception",
  typeOfSamplesTaken: "claim/type-of-samples-taken",
  numberOfFluidOralSamplesException: "claim/number-of-fluid-oral-samples-exception",
  numberOfFluidOralSamples: "claim/number-of-fluid-oral-samples",
  numberOfBloodSamplesException: "claim/number-of-blood-samples-exception",
  numberOfBloodSamples: "claim/number-of-blood-samples",
  numberOfSamplesTestedException: "claim/number-of-samples-tested-exception",
  numberOfSamplesTested: "claim/number-of-samples-tested",
  numberOfSpeciesException: "claim/number-of-species-exception",
  numberOfSpeciesPigsException: "claim/number-of-species-pigs-exception",
  numberOfSpeciesSheepException: "claim/number-of-species-sheep-exception",
  numberOfSpeciesTested: "claim/number-of-species-tested",
  piHuntAllAnimalsException: "claim/pi-hunt-all-animals-exception",
  piHuntAllAnimals: "claim/pi-hunt-all-animals",
  piHuntException: "claim/pi-hunt-exception",
  piHuntRecommendedException: "claim/pi-hunt-recommended-exception",
  piHuntRecommended: "claim/pi-hunt-recommended",
  piHunt: "claim/pi-hunt",
  pigsElisaResult: "claim/pigs-elisa-result",
  pigsGeneticSequencing: "claim/pigs-genetic-sequencing",
  pigsPcrResult: "claim/pigs-pcr-result",
  sameHerdException: "claim/same-herd-exception",
  sameHerd: "claim/same-herd",
  selectTheHerdDateException: "claim/select-the-herd-date-exception",
  selectTheHerdException: "claim/select-the-herd-exception",
  selectTheHerd: "claim/select-the-herd",
  sheepEndemicsPackage: "claim/sheep-endemics-package",
  sheepTestResults: "claim/sheep-test-results",
  sheepTests: "claim/sheep-tests",
  speciesNumbersException: "claim/species-numbers-exception",
  speciesNumbers: "claim/species-numbers",
  testResults: "claim/test-results",
  testUrnException: "claim/test-urn-exception",
  testUrn: "claim/test-urn",
  vaccination: "claim/vaccination",
  vetName: "claim/vet-name",
  vetRcvs: "claim/vet-rcvs",
  vetVisitsReviewTestResults: "claim/vet-visits-review-test-results",
  whichSpecies: "claim/which-species",
  whichTypeOfReviewDairyFollowUpException: "claim/which-type-of-review-dairy-follow-up-exception",
  whichTypeOfReviewException: "claim/which-type-of-review-exception",
  whichTypeOfReview: "claim/which-type-of-review",
  youCannotClaim: "claim/you-cannot-claim",
};

export const poultryClaimRoutes = {
  biosecurity: "/poultry/biosecurity",
  biosecurityUsefulness: "/poultry/biosecurity-usefulness",
  changesInBiosecurity: "/poultry/changes-in-biosecurity",
  checkAnswers: "/poultry/check-answers",
  checkSiteDetails: "/poultry/check-site-details",
  confirmation: "/poultry/confirmation",
  costOfChanges: "/poultry/cost-of-changes",
  dateOfVisit: "/poultry/date-of-visit",
  enterSiteName: "/poultry/enter-site-name",
  enterCphNumber: "/poultry/enter-cph-number",
  enterSiteDetails: "/poultry/enter-site-details",
  interview: "/poultry/interview",
  minimumNumberOfBirds: "/poultry/minimum-number-of-birds",
  selectPoultryType: "/poultry/select-poultry-type",
  selectTheSite: "/poultry/select-the-site",
  siteOthersOnSbi: "/poultry/site-others-on-sbi",
  vetName: "/poultry/vet-name",
  vetRcvs: "/poultry/vet-rcvs",
};

export const poultryClaimViews = {
  biosecurity: "poultry/claim/biosecurity",
  biosecurityException: "poultry/claim/biosecurity-exception",
  biosecurityUsefulness: "poultry/claim/biosecurity-usefulness",
  cannotContinueTimingRules: "poultry/claim/cannot-continue-timing-rules",
  changesInBiosecurity: "poultry/claim/changes-in-biosecurity",
  checkAnswers: "poultry/claim/check-answers",
  confirmation: "poultry/claim/confirmation",
  costOfChanges: "poultry/claim/biosecurity-cost-of-changes",
  dateOfVisit: "poultry/claim/date-of-visit",
  interview: "poultry/claim/interview",
  enterSiteName: "poultry/claim/enter-site-name",
  enterCphNumber: "poultry/claim/enter-cph-number",
  minimumNumberOfBirds: "poultry/claim/minimum-number-of-birds",
  minimumNumberOfBirdsException: "poultry/claim/minimum-number-of-birds-exception",
  selectPoultryType: "poultry/claim/select-poultry-type",
  selectTheSite: "poultry/claim/select-the-site",
  siteOthersOnSbi: "poultry/claim/site-others-on-sbi",
  vetRcvs: "poultry/claim/vet-rcvs",
  vetName: "poultry/claim/vet-name",
};

export const poultryApplyUrls = [...Object.values(poultryApplyRoutes)];
export const poultryClaimUrls = [...Object.values(poultryClaimRoutes)];
export const allPoultryRoutes = [
  ...poultryApplyUrls,
  dashboardRoutes.poultryManageYourClaims,
  ...poultryClaimUrls,
];
